# Generated by Django 4.2.23 on 2025-07-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('verse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='bible.verse')),
            ],
        ),
    ]
