# Generated by Django 4.2.23 on 2025-07-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_versevector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versevector',
            name='vector',
            field=models.TextField(),
        ),
    ]
